package aot.util.ecm.domain;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-07-28T15:13:54.794+07:00
 * Generated source version: 3.3.2
 *
 */
@WebServiceClient(name = "OTRIC",
                  wsdlLocation = "file:ECM.wsdl",
                  targetNamespace = "http://tempuri.org/")
public class OTRIC extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "OTRIC");
    public final static QName OTRICSoap12 = new QName("http://tempuri.org/", "OTRICSoap12");
    public final static QName OTRICSoap = new QName("http://tempuri.org/", "OTRICSoap");
    static {
        URL url = null;
        try {
            url = new URL("file:ECM.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OTRIC.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:ECM.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OTRIC(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OTRIC(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OTRIC() {
        super(WSDL_LOCATION, SERVICE);
    }

    public OTRIC(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public OTRIC(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public OTRIC(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns OTRICSoap
     */
    @WebEndpoint(name = "OTRICSoap12")
    public OTRICSoap getOTRICSoap12() {
        return super.getPort(OTRICSoap12, OTRICSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OTRICSoap
     */
    @WebEndpoint(name = "OTRICSoap12")
    public OTRICSoap getOTRICSoap12(WebServiceFeature... features) {
        return super.getPort(OTRICSoap12, OTRICSoap.class, features);
    }


    /**
     *
     * @return
     *     returns OTRICSoap
     */
    @WebEndpoint(name = "OTRICSoap")
    public OTRICSoap getOTRICSoap() {
        return super.getPort(OTRICSoap, OTRICSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OTRICSoap
     */
    @WebEndpoint(name = "OTRICSoap")
    public OTRICSoap getOTRICSoap(WebServiceFeature... features) {
        return super.getPort(OTRICSoap, OTRICSoap.class, features);
    }

}
